name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check compilation
      run: |
        node --check server.js
        echo "✅ Backend compilation successful"
        
    - name: Run ESLint
      run: npm run lint
      
    - name: Check Prettier formatting
      run: npm run format
      
    - name: Start server and test health endpoint
      run: |
        npm start &
        sleep 5
        curl -f http://localhost:3000/api/health || exit 1
        echo "✅ Server health check passed"
